### ISSUE TITLE
Make check for update functioning

### ISSUE THREAD

**Issue by darbuo** [jdemetra/jdemetra-app#116]

**Comment by charphi** [comment]
Problem also referenced at https://github.com/jdemetra/jdemetra-core/issues/96

**Comment by charphi** [comment]
![check for updates](https://cloud.githubusercontent.com/assets/8778378/11739271/840c7f24-9fea-11e5-91e4-4f87da1425aa.png)

**Comment by charphi** [comment]
This menu item is removed (5bdd814ae0c76bbce6d94f6274b85fa6c83a80f7) until we have a proper mechanism for updates.
