### ISSUE TITLE
SAUG ideas for development: Deleting time series

### ISSUE THREAD

**Issue by FaizAlsuhail** [jdemetra/jdemetra-app#118]
There was a wish that here would be a alert before one can delete a time series. It is easy to accidentially deleted too many time series.

Perhaps a pop-up window asking "Are you sure you want to delete series X, Y and Z from your project" would be easy to implement?

**Comment by FaizAlsuhail** [comment]
This suggestion received one "high", one "medium" and one "low" priritization during the SAUG meeting in Luxembourg, December 2015.

**Comment by maggima** [comment]
Can you please give the locations/components in the application where the message would be useful ?

**Comment by mancag** [comment]
For example, I open a multi-document and there is a list of time series. I choose some of them -> right click -> Edit -> Delete. I get a message: "Are you sure you want to delete the selected items?" One could accidently delete more series than he wanted to (this happened to me a few times). So it would be better to change the message: e. g. "Are you sure you want to delete the following items: ...?"
In my opinion, this suggestion would be good for other related examples.

**Comment by maggima** [comment]
The user will be presented with the following message when deleting objects in Multi processing :

![delete_message](https://cloud.githubusercontent.com/assets/10207848/12418895/c909b0ec-beb2-11e5-81b8-baeb45689505.png)

The selected items can be adjusted from that dialog
