### ISSUE TITLE
Missing label in JTsGrid single mode

### ISSUE THREAD

**Issue by charphi** [jdemetra/jdemetra-app#12]
JTsGrid doesn't display the column label in single mode with yearly frequency.

**Comment by Immurb** [comment]
The formatPeriod-method in TsPeriod  seems like it returns an empty String for yearly frequencies so the label is also empty. Isn't it more like a choice of design rather than a bug?

**Comment by charphi** [comment]
Indeed, but the grid header has an small size when there is no label in it and the result looks weird.
