### ISSUE TITLE
SAUG ideas for development: "Save apply" -buttons in multi docs

### ISSUE THREAD

**Issue by FaizAlsuhail** [jdemetra/jdemetra-app#122]
This suggestion was rated:
- "high" 3 times
- "medium" 2 times.

**Comment by charphi** [comment]
![apply-save](https://cloud.githubusercontent.com/assets/8778378/12260280/5c60ce9a-b91b-11e5-8eb2-57739a840230.png)

**Comment by SylwiaGrudkowska** [comment]
It would rather generate more confusion... the set of buttons called "Apply", "save" and Save Apply" ismisleading. Once it is implemented, the users would say that incidentaly they saved what they didn't intended to.

**Comment by palatej** [comment]
One of the current problem is due to the fact that modifications are silently lost when you select another item in a multi-document. It is corrected in 2.1RC4
