### ISSUE TITLE
SAUG ideas for development: Calendars

### ISSUE THREAD

**Issue by FaizAlsuhail** [jdemetra/jdemetra-app#125]
The idea is to define national calendar regressors as separate file. This way it would be possible use the calendar in new workspaces

Suggestions on (national) calendars appeared multiple times. Their combined ratings are the following: 
- "High" 3
- "Medium" 2
- "Low" 1

**Comment by charphi** [comment]
![import calendars](https://cloud.githubusercontent.com/assets/8778378/12260603/e814e83a-b91c-11e5-83e9-bb8a097cacfd.png)
