### ISSUE TITLE
SAUG ideas for development: "A customized diagnosis table"

### ISSUE THREAD

**Issue by FaizAlsuhail** [jdemetra/jdemetra-app#134]
The user should be able to choose which diagnostics you want to focus on. To make it easier, there should be an option to choose, what diagnostics are presented in the users customized diagnosis table. 

This initiative was rated:
- High: 3 times
- Medium: 2 times
- Low: 1 time.

**Comment by SylwiaGrudkowska** [comment]
Suggested change for this requirement: add a panel to the output tree with the most important measures  (possibly customised). Such plugin (without customisation) is being developed by BBk.

**Comment by palatej** [comment]
NBB will add in the matrix view a customizable panel with a selection of measures
