### ISSUE TITLE
SAUG ideas for development: "Dealing with prior adjusment files"

### ISSUE THREAD

**Issue by FaizAlsuhail** [jdemetra/jdemetra-app#148]
This initiative was rated:
- Medium: 2 times.

**Comment by charphi** [comment]
To be discussed with SACE

**Comment by duncanelliott** [comment]
I would like to see this as an option before 3.x if possible (via fixed coefficients in user defined regressors?). Is there a case for not being able to meet the guidelines if this is not included? For example, if there was a trading day effect in a series, this then stops at a particular point in time and you only want to estimate the effect using the span for which it was present. Other cases are when you know the actual  value of an effect, why would you want to estimate it in a regression each time?

**Comment by palatej** [comment]
See also #51.
Simplified approach will be available in 2.2

**Comment by palatej** [comment]
See #275
