### ISSUE TITLE
SAUG ideas for development: "The "+" -button in the Spesifications window should remain open""

### ISSUE THREAD

**Issue by FaizAlsuhail** [jdemetra/jdemetra-app#154]
In addition the important parameters would be Bold.

This initiative was rated:
- Medium: 2 times
- Low: 1 time

**Comment by charphi** [comment]
+ change label to show non-default values?

**Comment by SylwiaGrudkowska** [comment]
The whole idea of output tree is this fold/unfold functionality. When it stays unfolded the list of output items is long, difficult to scan, groups of items in the end of the tree (benchmarking, diagnostic) would not be visible on the first grance (the user need to scorll to see them). I would advise not to introduce such functionality.

**Comment by palatej** [comment]
It would need substantial changes (we use an existing library) for a quite limited benefit. So, I also propose to close this issue (for the moment)
