### ISSUE TITLE
Bug Outliers can be specified outside the timeseries

### ISSUE THREAD

**Issue by ChristianeHofer** [jdemetra/jdemetra-app#180]
The results will be influenced by these pre-specified outliers but they are not displayed in the Pre-processing/ regressors results. Furthermore it seems to suppress the automatic outlier detection.

**Comment by palatej** [comment]
Corrected in jdemetra-core/#109. The user can still define outliers outside the estimation span (which is not always known), but those outliers will not be taken into account. Moreover, the outliers detection now works correctly in such cases.
