### ISSUE TITLE
ECB proposal for enhancement: Display info about seasonal filters by period

### ISSUE THREAD

**Issue by SylwiaGrudkowska** [jdemetra/jdemetra-app#192]
It would be helpful for us if information about seasonal filters applied to each period is clealy isplauyed in the interface (Decomosition  (X11) -> Final filters)> Now when different filters are used, information: "Mixed filters" is dislpayed. We would like to have it clearly displayed: e.g.: Jan - 3_3, Feb - 3_5,...

**Comment by palatej** [comment]
A more general mechanism to propagate intermediary information of the X11 processing has been developed (in a specific branch). It should be integrated in 2.2. Workload: 5 days

**Comment by ChristianeHofer** [comment]
We could do that.

**Comment by Immurb** [comment]
Can be closed.
