### ISSUE TITLE
Suggestion for development: Trading/Working days

### ISSUE THREAD

**Issue by FaizAlsuhail** [jdemetra/jdemetra-app#193]
At the moment it is possible to create a calendar, where a holiday is valid only for a certain period of time. For example, if I wish to use a calendar in which June 6th is a holiday from 1997-2007, I can do it. 

**I would like to have a similar option for the Trading/Working days**. 

This would be an interesting option for the retail series. As the shopping hours are becoming increasingly liberal it would be worthwhile to consider an option where some (early) periods would have a Trading/Working day correction and other (later) periods not.

**Comment by palatej** [comment]
This issue corresponds to the "change of regime" facility available in the original X13. It is part of the re-design of the regression variables planned for 3.0. Global workload for the regression variables: 60 days
