### ISSUE TITLE
missing menu on mac os

### ISSUE THREAD

**Issue by leilapeltier** [jdemetra/jdemetra-app#207]
Hi, 
I am using the JDemetra v2.1 RV3 on a mac Yosemite with 
Product Version: JDemetra+ 2.1.0-rc3
Java: 1.7.0_79; Java HotSpot(TM) 64-Bit Server VM 24.79-b02
Runtime: Java(TM) SE Runtime Environment 1.7.0_79-b15
System: Mac OS X version 10.10.5 running on x86_64; UTF-8; fr_FR (nbdemetra)
I can't see the menu 

![capture d ecran 2016-03-15 a 13 44 57](https://cloud.githubusercontent.com/assets/17809892/13778129/476a5c20-eab4-11e5-86da-3cc614df3173.png)

Thanks in advance

**Comment by charphi** [comment]
The menu should be visible now.
(Tested with JD+ 2.2.0-SNAPSHOT on Java 8 Mac OS X Sierra)
