### ISSUE TITLE
Some setting change when selected just before clicking 'apply'

### ISSUE THREAD

**Issue by SA-StatNL** [jdemetra/jdemetra-app#237]
When selecting the LSigma or Usigma fields (which are 1,5 and 2,5 by default), followed by clicking 'apply' immediately, they change to 15 or 25, respectively. The same holds for TCrate, which changes from 0,7 to 7.

**Comment by ChristianeHofer** [comment]
I can reproduce this bug, when I use Windows 7 with German regional and language settings. These wrong values are used for the calculation too.  Please try to change the language and regional settings to English, this could be a quick solution. We will fix the bug in the next release.

**Comment by charphi** [comment]
Related to #205
