### ISSUE TITLE
keep user regressors 

### ISSUE THREAD

**Issue by reginasoares** [jdemetra/jdemetra-app#243]
It is not an issue, it is an enhancement or a wish...
Is it possible to keep defined user regressors (calendar or others)  in "memory" in order these regressors will be reloaded when starting a new workspace/processing?
That's, having different default utilities defined by the user.
Thank you for your attention

**Comment by charphi** [comment]
Currently not, but it could be achieved by using the import/export mechanism already available for calendars.

**Comment by reginasoares** [comment]
Thank you very much for your answer Philippe. 

For calendars, click right the option import only admits configs files extension (I don't know what kind of file is).

I only can use my own regressors (in version 2.1.0) if I  create, under Variables, a New Variables Window and copy my regressors from an excel file to the Grid Window and from the Grid Window to this Variables Window.
I didn't find any other way, but maybe it exists.

**Comment by reginasoares** [comment]
The export only exists under the option Calendars, not for user Variables.

**Comment by reginasoares** [comment]
Thank you again Philippe.

**Comment by charphi** [comment]
Currently, the import/export only exist for calendars.
The idea is to add this behavior to variables in a next release of JDemetra+.

**Comment by charphi** [comment]
Done by 356456d
