### ISSUE TITLE
Series span "from" to "between"

### ISSUE THREAD

**Issue by IGetins** [jdemetra/jdemetra-app#245]
I am using JDemetra+2.1.0 version, excel files as an input. If I open a previously saved workspace which contains SAProcessing with a time series which Series span is "from", then it is no possible to change the Series span to “between”. An error occurs (right lower corner – red circle). This is true for tramo/seats and x13. There is no problems if the workspace wasn't saved and reopened.

**Comment by palatej** [comment]
Corrected in ../jdemetra-core/#176. See also #254
