### ISSUE TITLE
Incorrect message during Output file creation in case of no write access to the output folder.

### ISSUE THREAD

**Issue by kalnikh** [jdemetra/jdemetra-app#249]
When you click on output and then choose the output type(for instance CSV), then there is a possibility to choose folder. If you choose, the folder path here and save the output, you get the notification that "CSV Successfully generated"

However, If the user has no write access to the chosen folder the application still informs the user that the export/save was successful. But the content is not saved to the output folder due to not having write access.

**Comment by palatej** [comment]
Information about output is indeed currently quasi-missing (or misleading). We will provide more feedback (success/failure, where... ) in the next release.

**Comment by charphi** [comment]
Done by 623727f
