### ISSUE TITLE
Easter effect specification X13

### ISSUE THREAD

**Issue by ThomasBalcone** [jdemetra/jdemetra-app#250]
Hi,

there is problems with Easter in the specifications : there is no control on the value of the parameter "Duration" (one can enter 30 for example and no error messages appear).

Moreover, with the parameter "Duration=8", I don't understand the value for March 2007 and 2012. For theses years, Easter is on the 8th April. So, if I understand well the computation method of the regressor, the value for these years should be the same as the one for the other years with no days in March among the 8 days before Easter (Easter included) (for example : the years 2000, 2001).

Thank you in advance for your answer,

Best regards,
Thomas

**Comment by palatej** [comment]
In the computation of the Easter effect, Easter is not included, which means that the effect in 2000 and in 2007 will differ. See ec.tstoolkit.timeseries.regression.EasterVariable for the exact computation. I will add a test on the parameter (which should be in [1,25].

**Comment by palatej** [comment]
Corrected in ../jdemetra-core/#176
