### ISSUE TITLE
D16a forecast not showing in table

### ISSUE THREAD

**Issue by AdelBosch** [jdemetra/jdemetra-app#252]
I find that the D16a seasonal factor forecast (in the decomposition tables) is giving me zeros and no forecast factors.

**Comment by ChristianeHofer** [comment]
This is a known bug, we will fix it for the next release.

**Comment by AdelBosch** [comment]
Thank you!

On Wed, Nov 16, 2016 at 11:48 AM, Christiane Hofer <notifications@github.com
