### ISSUE TITLE
incoherence between "independence" in "main results" and "Ljung-Box (24)" in "Residuals>Statistics"

### ISSUE THREAD

**Issue by ThomasBalcone** [jdemetra/jdemetra-app#259]
Hi,

There is an incoherence between "independence" in "main results" and "Ljung-Box (24)" in "Residuals>Statistics". The p-values should be indeed the same ones according to the reference manual (lag=24).

Why is there a difference?

Thank you in advance for your answer.

Best regards,
Thomas

**Comment by palatej** [comment]
Already corrected in the code in development
