### ISSUE TITLE
Problem with the export of series when we put "-2" in "Forecasts horizon"

### ISSUE THREAD

**Issue by ThomasBalcone** [jdemetra/jdemetra-app#269]
Hi, 

when we put "-2" in "Forecasts horizon" in the panel "Specifications", we get only the values of the forecasts for one year in the output files "ycal_f", "out_s_f" and "cal_f".

Thank you in advance for your answer,

Best regards,
Thomas

**Comment by palatej** [comment]
Same as issue 173
