### ISSUE TITLE
defining outliers in JD+ 2.1

### ISSUE THREAD

**Issue by alyleon314** [jdemetra/jdemetra-app#280]
Perhaps it is possible to add the "Clear all" functionality when specifying outliers through JD+ 2.1 GUI? Or at least make it possible to delete more than one outlier with the "-" icon.

**Comment by maggima** [comment]
Hello,

Thank you for your suggestion.
This feature will be added and be available in the next release (2.2.0) of JDemetra+.

Regards,

Mats
