### ISSUE TITLE
bug with the Henderson filter

### ISSUE THREAD

**Issue by ThomasBalcone** [jdemetra/jdemetra-app#284]
Hello,

I have noticed a bug in JD+ when you selected a special order for the Henderson filter in the specifications panel : the seasonal adjustment is done with the automatic Henderson filter even if the corresponding box is unchecked and another order for the Henderson filter is specified.

You will find an example of a series for which this bug has happened in the attached file :
SAProcessing = "industrie"
series = "IND_IPIN4 - RF1107"

Thank you in advance for your help.

Best regards,
Thomas Balcone

[deuxieme_candidat.zip](https://github.com/jdemetra/jdemetra-app/files/761334/deuxieme_candidat.zip)

**Comment by ChristianeHofer** [comment]
Dear Thomas,
In SAProcessing\industrie.xml in
the pointspec  <item name="x11">
                        <subset/>
                    </item>
is empty for IND_IPIN4 - RF1107. This is used for the calculation when you open the Workspace.
I don't know how this could happen. You could change something in the spec Save it, then it should work.  
Regards Christiane

**Comment by ThomasBalcone** [comment]
Dear Christiane,

thank you for your answer. The problem is that when I use the cruncher, the SA series which is computed doesn't take into account the Henderson filter that I have specified. It is the automatic Henderson filter which is taken into account...

So, it is very problematic when you use the cruncher in your production process.

Best regards,
Thomas

**Comment by palatej** [comment]
Hello Thomas,

I checked with the cruncher. I don't see the problem. If you write the xml yourself, be sure that it is well-formed:
you should have somewhere in the spec something like

...
<item name="x11">
  <subset>
    <item name="mode">
      <string>Multiplicative</string>
    </item>
    <item name="trendma">
      <integer>45</integer> (for instance)
    </item>
...

Jean

**Comment by ThomasBalcone** [comment]
Hello Jean,

I'm sorry. I made a mistake in my test on the cruncher. It is indeed good for the cruncher : the SA series which is computed thanks to it is the one which takes into account the Henderson filter that I have manually specified.

So, it is "only" a problem on the application.

Best regards,
Thomas
