### ISSUE TITLE
Error message when trying to adjust model span (bug)

### ISSUE THREAD

**Issue by SA-StatNL** [jdemetra/jdemetra-app#285]
I get an error message (jave error) when I go through the following actions in JDemetra + (version 2.1):
- For any series within a multi-document of a certain workspace I choose a model span with type: FROM and Start: YYYY-MM-DD
- I click apply and save the specifications with the adjusted model span for these series.
- I save the workspace and close JDemetra+
- I open JDemetra+ and open the workspace and multi-document with the adjusted model span
- When I now try to adjust the model span type to something else (e.g. TO or BETWEEN) I'm getting an error message icon in corner right-below stating: Unexpected Exception / Show and Report Problem / java.lang.NullPointerException

I have added the Exception Report.

[Exception Demetra.docx](https://github.com/jdemetra/jdemetra-app/files/766998/Exception.Demetra.docx)

**Comment by palatej** [comment]
Thank you for your message. It is corrected in JD+ 2.2 (soon in pre-release)
