### ISSUE TITLE
Workspace empty

### ISSUE THREAD

**Issue by sungreen** [jdemetra/jdemetra-app#290]
Installation on linux gentoo with package oracle-java-bin. After start of the program the workspace empty window.

**Comment by charphi** [comment]
What do you mean by empty? Could you send a screenshot?

By the way, you can look at the logs to pinpoint the problem:
https://github.com/jdemetra/jdemetra-app/wiki/Quick-install-guide#troubleshooting

**Comment by sungreen** [comment]
log: http://pastebin.com/RyAZYWtp
screens: https://youtu.be/_Sd4uTzUtcA

**Comment by charphi** [comment]
The problem comes from a bug in the application.

Here is a temporary workaround: set the environment variable `XDG_DOCUMENTS_DIR` to any folder before launching JDemetra+.

For example: `$ export XDG_DOCUMENTS_DIR=~/documents`

**Comment by sungreen** [comment]
Thanks. Now works!
I have added here such lines:

export HISTCONTROL=ignoredups
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on"
export XDG_DOCUMENTS_DIR=~/documents

**Comment by charphi** [comment]
You are welcome.
This bug will be fixed in the next release.
