### ISSUE TITLE
Outliers in Summary window

### ISSUE THREAD

**Issue by IGetins** [jdemetra/jdemetra-app#297]
When the data is refreshed with an added period, the summary window about the whole file shows incorrect Outlier numbers. (example, There are more than 72 outliers in the file, but it shows only 1)
![image](https://cloud.githubusercontent.com/assets/22952087/23456388/e5deef52-fe7b-11e6-9dcf-98b9a91b0cd0.png)

**Comment by palatej** [comment]
Corrected in #216 of jdemetra-core
