### ISSUE TITLE
user-defined variables are not correct saved in WS (async?)

### ISSUE THREAD

**Issue by ChristianeHofer** [jdemetra/jdemetra-app#302]
First I drag and drop my data (several timesseries from excel spread Sheet) to a new user-defined variable.I used ony the first one, fine. 
Then I saved and re-opend the workspace, which has some problems because the date from the second userdefine-variable was not saved correctly.
Indeed the data were never loaded, we got the impression this is a side effect from the async load of data. 
Do you need further informations?
Regards Christiane

**Comment by charphi** [comment]
Could you describe the problem when you re-open the workspace ?

**Comment by ChristianeHofer** [comment]
When I put new a vars-1 together it looks like this: 
![image](https://cloud.githubusercontent.com/assets/10463108/23908230/b3e7f3a6-08d3-11e7-9dd8-135f0c83be74.png)
Save the Workspace/Open Workspace
[WS.zip](https://github.com/jdemetra/jdemetra-app/files/841884/WS.zip)
Double click on Vars-1:

Exception: 
[WS2_Exception.txt](https://github.com/jdemetra/jdemetra-app/files/841867/WS2_Exception.txt)

**Comment by charphi** [comment]
NullPointerException is already fixed by bff089d.
There are still other problems linked to async loading. I'm searching for a solution.

**Comment by ChristianeHofer** [comment]
This is the important point for me. There might also be other side effecs from the async loading with multi-processing.

**Comment by charphi** [comment]
Problem solved in latest snapshot.
