### ISSUE TITLE
Changing the font size in JDemetra GUI

### ISSUE THREAD

**Issue by ladidom** [jdemetra/jdemetra-app#307]
Hi,
Would it be possible to change/increase the font size in the GUI?

Thanks,
Dominique

**Comment by palatej** [comment]
We will introduce that enhancement in 3.0 (too much work to put it in 2.2).

**Comment by charphi** [comment]
@ladidom : you can test this improvement with the latest snapshot of JD+:
https://oss.jfrog.org/artifactory/oss-snapshot-local/eu/europa/ec/joinup/sat/nbdemetra-app/2.2.1-SNAPSHOT/nbdemetra-app-2.2.1-20171013.083108-2.zip

To change the font size, you can either:
- right-click on a report and select `Zoom` 
- go to `Tools > Options > Demetra UI > Html Font Size`
