### ISSUE TITLE
I can't delete a multi-document

### ISSUE THREAD

**Issue by ChristianeHofer** [jdemetra/jdemetra-app#313]
I did the follwing steps:
- Open a Workspace with several multi-documents.
- Delete one multi-document 
- Can't see it in the UI
- save the workspace
- close und open JD+
- reopen the Workspace
- the deleted multi-document is back in the workspace, the files were never deleted.
  Did I miss something?
Regards Christiane

**Comment by charphi** [comment]
I've just tested and I confirm that the deletion is not performed when saving the workspace.

Note that this bug already exists in JD+ v2.1.0 in a slightly different way: 
a "deleted" workspace item is only removed from the workspace index, not the file system.

**Comment by charphi** [comment]
This should work as expected now.
