### ISSUE TITLE
Bug importing specifications

### ISSUE THREAD

**Issue by soledad-saldana** [jdemetra/jdemetra-app#315]
When we import a previously exported specification, we have observed the following problems:
-  Trading day options are not always correctly imported. In particular, it occurs when **automatic** option is different from _Unused_
-  Easter option is not correctly imported. It always appears as _Unused_.
-  _User defined variables_ included in imported specifications are not identified even if those variables are defined before using the specification. 

Regards
Statistics Spain

**Comment by palatej** [comment]
Corrected in #320 .
The previous implementation used an obsolete (and incomplete) file format. Be aware that you will not be able to import with the new version files saved with the old version. 
The user defined variables are saved in a separate file. The variables referenced in imported specifications must be present in the software if you want to use those specifications.
