### ISSUE TITLE
Bug in new section Matrix in Diagnostics node

### ISSUE THREAD

**Issue by soledad-saldana** [jdemetra/jdemetra-app#317]
We have detected that when we click the Matrix section and then we click any other results section, the identified model is changed automatically to (0,1,1)(0,1,1).

Regards
Statistics Spain

**Comment by palatej** [comment]
Hi
Could you explain in more details the problem and send some snapshots: I have not been able to detect the exact problem.
Thank you in advance.

Jean

**Comment by soledad-saldana** [comment]
Hi,
Sorry, I'll try to explain the problem better. After creating a multidocument, we  observe the identified Arima model in the Pre-procecessing node. Then we click the Matrix section and back to the Pre-processing node and the identified model has been changed (the model is not always moved to (0,1,1)(0,1,1) as I said before, but the orders of the models are modified) .
I attach some snapshots that show the problem.

![inicialmodel](https://cloud.githubusercontent.com/assets/17177915/25223371/81d68aa8-25bb-11e7-8a1f-a30ce1598716.jpg)
![matrixsection](https://cloud.githubusercontent.com/assets/17177915/25223382/8bdfb13c-25bb-11e7-8005-c9b31fc70e06.jpg)
![modelafterclickmatrixsection](https://cloud.githubusercontent.com/assets/17177915/25223390/90918fac-25bb-11e7-826c-7caa2a4f9d87.jpg)

Thank you very much.

Regards
Soledad Saldaña(Statistics Spain)

**Comment by palatej** [comment]
OK. Thank you.
Corrected in #319
