### ISSUE TITLE
SAUG Bug report in version 2.2.0: Specification  

### ISSUE THREAD

**Issue by lovix** [jdemetra/jdemetra-app#322]
![attach1](https://cloud.githubusercontent.com/assets/22325089/25327402/46f15424-28d4-11e7-997b-cd70c60c9161.png)
![attach2](https://cloud.githubusercontent.com/assets/22325089/25327401/46f0291e-28d4-11e7-82dc-22fd0d356bf3.png)
![attach3](https://cloud.githubusercontent.com/assets/22325089/25327400/46ee0d8c-28d4-11e7-9bd2-7b86cf0a34f6.png)

Dear Developers!

In tramoseats specification, if RSAfull specification is cloned, than the tradingDays, Leap year and RegressionTestType options are inactive (see attach1.png). If Option is changed to UserDefined (see attach2.png), than change back to Holidays, they become active (see attach3.png). 

Maria and Gábor

**Comment by palatej** [comment]
Hi Maria and Gabor,

The fact that some parts of the calendar specification are disabled is linked to the use or not of automatic identification of trading days ("automatic" field). When automatic identification is enabled (which is the case in RSAfull), you can't specify the trading days option, leap year and regression tests. To enable those items, you have to switch off the automatic field. This is also done when you use user-defined regression variables (the software is then not able to make automatic selection).
Of course we could automatically switch on automatic detection when you select "holidays" or "default", but it can also be annoying.
So, this is not a bug, just a choice.

Best regards

Jean
