### ISSUE TITLE
Question about output items

### ISSUE THREAD

**Issue by lovix** [jdemetra/jdemetra-app#323]
Dear Developers!

In Reference Manual table 7.15 the meaning of the output itemes can be found. In that table we can found, that "l" is Linearized series (transformed) and "y_lin" is Linearized series (not transformed). We thought that the "l" is logarithm of "y_lin" when we use multiplicative model, but we found that there is no difference between the two variables. The results are the same for additve modell and multiplicative model too. We find this problem while we testing version 2.2.0 RC 1 but version 2.1.0 generates the same outputs. 

Do we misunderstanding something, or should these two results different when we use multiplicative model?    

Thanks for your answer,

Maria and Gábor

**Comment by palatej** [comment]
Hi Maria and Gabor,

The documentation is not correct: l is the linearized series = interpolated series, in logs when the model is multiplicative, corrected for all regression effects. y_lin is the same interpolated series (in logs for multiplicative models), corrected for all regression effects except regression effects that are not attributed to a specific component. 
It should be noted that regression variables that are not associated to a specific component are just used to improve the modelling; however, they are not removed from the series and they are integrated in the decomposition. So, the decompositions (X11, SEATS) will use y_lin.
Of course, in most cases, l = y_lin
