### ISSUE TITLE
Unstable number of outliers

### ISSUE THREAD

**Issue by HienPhamInsee** [jdemetra/jdemetra-app#324]
Hi,
I encountered a problem quite disturbing. I use different sets of calendar regressors and let JD+ find the automatic Reg-ARIMA model. For one series, IPI branch 2811, there are no calendar effects detected for any set of regressors. So JD+ outputs a Reg-ARIMA model without calendar regressors. Nevertheless, I don't have the same Reg-ARIMA model, it depends on the set of regressors tested - even if the regressors are rejected. It seems to me that we should have the same Reg-ARIMA model. The example is in the workspace attached :
First model (tested with one calendar regressor) : Arima = airline, 16 outliers detected and no td effect ;
Second model (2 regressors tested) : (0,1,1)(0,1,0), 25 outliers  and no td effect ;
Third model (5 regressors tested) : airline, 12 outliers  and no td effect ;
Last model (calendar option put to None) : airline, 16 outliers detected and no td effect.
Why the number of outliers change so much when there are no calendar regressors in the Reg-ARIMA model in each case. 
Thanks,
Hien
[UnstableModel.zip](https://github.com/jdemetra/jdemetra-app/files/969859/UnstableModel.zip)

**Comment by palatej** [comment]
Hi Hien,

The current RegArima modelling  is indeed unstable, especially when you have many outliers. The final model depends on the whole path used during the automatic identification procedure. So, starting with or without regression variables, with or without pre-specified Arima orders... might lead to rather different models. For the time being - using the procedures of the original software - the only thing that we could do is to give information on the different steps of the processing; in that way, you will be able to understand in a better way the differences. Future versions - with a new automatic identification procedure - should try to lead to more robust solutions (-> JD+ 3.0).

**Comment by HienPhamInsee** [comment]
Thanks for your reply.
The diagram attached is from one of your slides (JCS 2016).
I understand from this diagram that the outliers detection is done in any case with the regression variables (that why we can have a different number of outliers). And the decision to keep or not the regression variables is taken only at the step "Model Cheks". Am I right ?

![reg-arima diagram](https://cloud.githubusercontent.com/assets/12731343/25626230/21f21352-2f5f-11e7-8440-fd5421a54531.JPG)

**Comment by palatej** [comment]
The diagram is a simplified view of the procedure. The regression variables are tested at different points: before the first outliers detection, in the model checks... Outliers detection is also processed several times (except when you specify the ARIMA orders). Getting details on the actual steps of an estimation could be useful...

**Comment by HienPhamInsee** [comment]
Thanks.
Can you tell me where can I get the details ? Is there a paper available in Github ?

**Comment by palatej** [comment]
All the details are in the code...
More seriously, we will write such documents for the new procedure of JD+ 3.0.
