### ISSUE TITLE
Bug in the CSV matrix output 

### ISSUE THREAD

**Issue by HienPhamInsee** [jdemetra/jdemetra-app#325]
Hi,
You can find attached the workspace in which there is a problem with the export of the CSV matrix (JD+ 2.1). The last series of the multi-document is very short (R11$B1109$TOT$I - 3 years), but the processing is done and we can output the SA series file. But when we try to output the CSV matrix there is an error message : 
![error message](https://cloud.githubusercontent.com/assets/12731343/25651892/abfce15e-2fe5-11e7-8ca2-707485221221.JPG)

Nevertheless, the output is done, but the CSV matrix file doesn't contain the 2 last series. 
[exemple_pb.zip](https://github.com/jdemetra/jdemetra-app/files/972719/exemple_pb.zip)

**Comment by palatej** [comment]
The problem is solved in 2.2
