### ISSUE TITLE
seasonal adjustment - TS Providers

### ISSUE THREAD

**Issue by pinkfairystardust** [jdemetra/jdemetra-app#329]
Hello!

I loaded some data from the provider in JDemetra 2,2, put them in a multi-document and calculate using a TramoSeats specification;
![image](https://cloud.githubusercontent.com/assets/26598367/25801512/93d237b8-33f6-11e7-93d1-baf90ff00f31.png)
see, there are 23 observations in my series from q1 2011 to q3 2016. Then I deleted the entrance for 01.04.2013. I used the reload option in the TS Providers and refreshed the series in the multidocument. Seasonal adjustment is still performed, displaying 23 observations like in the original series. 
![image](https://cloud.githubusercontent.com/assets/26598367/25801595/003ffb24-33f7-11e7-9df5-9311c445851b.png)

The same thing happens when in the original file I replace numbers for 01.01.2014 with character "a".
![image](https://cloud.githubusercontent.com/assets/26598367/25801840/31bbe7e8-33f8-11e7-80dd-bbbc3b099c8d.png)

It seems strange :) I think it should provide some sort of message displying there is missing data/wrong data type.

Kind regards,
Andreea Mirica
National Institute of Statistics, Romania

**Comment by palatej** [comment]
The number of observations includes missing values (which are considered as estimated parameters). 
It is indeed misleading. I will slightly change the likelihood statistics for models with missing values: they will appear explicitly and removed from the estimated parameters. To be noted that there will be an impact on the AIC..., which will be computed more correctly (the likelihood has been corrected for missing values; so they should not be taken into account in the number of estimated parameters). 
No impact on all the other results (actual model and decomposition....)
