### ISSUE TITLE
Residual Seasonality tests

### ISSUE THREAD

**Issue by pinkfairystardust** [jdemetra/jdemetra-app#332]
Hello!

I enabled the qs test and the f test in the advanced residual diagnosis and I used the RSAfull specification for calculation on 31 series ranging q1 1995 to q3 2016. There were 8 cases where only the F test on SA is computed like in the following example:

![image](https://cloud.githubusercontent.com/assets/26598367/25854171/c93b487c-34d7-11e7-8a2a-f12644338632.png)

Also, there were 7 cases where the qs on the Irregular, the F-test on SA and F-test on the Irregular were performed (qs on SA was not performed) like in the following example:

![image](https://cloud.githubusercontent.com/assets/26598367/25854346/57221698-34d8-11e7-8fc8-a9d5cbe6e831.png)

This seems strange :) but I can't figure why.

Kind regards,
Andreea Mirica
National Institute of Statistics Romania

**Comment by pinkfairystardust** [comment]
Also, I changed the RSA full specification: I added Romanian calendar and changed the time span to q1 2011 -q3 2016 (23 observations). I had some cases when only the F-test on SA was calculated despite the fact that when RSA full was used, qs test on SA, qs test of ir, F-test on SA and F-test on ir were computed.

**Comment by palatej** [comment]
Hi Andreea,

We avoid to compute statistics on components that are not significant, which explains the behaviour you mentioned.
More explicitly, the irregular component (I) is significant when:
a) multiplicative decomposition:
stdev(I)<0.005
b)additive decomposition:
stdev(I)/rms(SA)<0.005
For the SA component, the Ljung-Box test is applied on the differences.
So, we check that stdev(SA(t)-SA(t-1))/rms(SA) > 0.005.

To be noted that the tests might be applied on the last years. In that case, the significance of the components are computed on the restricted time span.

Best regards

Jean

**Comment by ChristianeHofer** [comment]
Hi Jean,
We had similar questions, when and why the QS and the F Tests are calculated or are not calculated on the SA and the i. Therefore we suggest to give more information in the output, if the test is not calculated. 

In addition, we had questions why the results of residual seasonality tests in different places (Diagnostics vs Diagnostics/Seasonality tests/Residual seasonality) are different. I think there is a need for more information on what is tested and which method is used. Furthermore the name for the configuration of the residual diagnostics doesn’t exactly match the name in the output. In general, the wording of “residual seasonality test” and “advanced residual seasonality test” is not consistent and a little confusing.

How should we proceed with this issue? 
Regards Christiane
