### ISSUE TITLE
Crash and Speed

### ISSUE THREAD

**Issue by veroniqueelter** [jdemetra/jdemetra-app#333]
JDemetra+ crashes more often and gets very slow at opening and for the first output if 2 versions are installed at the same time on a PC (e.g. version 2.1.0 and 2.2.0). This is a problem as we need the older version for the production process and the new version for testing purposes at the same time on the same PC (Java version used: Java: 1.8.0_92; Java HotSpot(TM) 64-Bit Server VM 25.92-b14)

**Comment by charphi** [comment]
By default, JD+ uses the same user dir for every versions.
But, it is possible to specify a separate user dir by editing the `default_userdir` property of the [config file](https://github.com/jdemetra/jdemetra-app/wiki/Quick-install-guide#a-few-tips ).
