### ISSUE TITLE
Values inserted as text in the series

### ISSUE THREAD

**Issue by veroniqueelter** [jdemetra/jdemetra-app#335]
Values inserted as text ('/) are automatically converted to values, but only the part before the decimal separator is taken into account.

**Comment by charphi** [comment]
Could you describe you problem?
Are you referring to the import of time series from an Excel file?
Which version of JDemetra+ are you using?

**Comment by veroniqueelter** [comment]
Yes, I am referring to the import of times series from an Excel file. 
I used the new test version JDemetra+2.2.0.

**Comment by charphi** [comment]
I can't reproduce your problem on my computer. It might be related to specific regional settings.

Anyway, the parsing of numeric values and dates from text is driven by the `Data format` option of the spreadsheet open dialog. You can try to tweak it until it works. 

You can also check the content of a spreadsheet by using the spreadsheet profiler (`Menu>Tools>Spreadsheet Profiler`).
