### ISSUE TITLE
TradingDays userVariables not possible to fix only one of them

### ISSUE THREAD

**Issue by ChristianeHofer** [jdemetra/jdemetra-app#342]
At the moment fixed regression coefficients have to be specified for all the trading-day variables. While this seems to be sensible for pre-specified trading-day and working-day variables, the restriction does not necessarily make sense for user-specified variables.

For instance it is possible to distinguish between working-day effects for different periods during the year by splitting regressors in a way that one regressor is intended to capture the effect of an additional working day in the months from January till November and another regressor the effect in December. Since the latter is very often assumed to be significantly smaller due to leave between Christmas and New Year irrespective of the number working days this can lead to very different results.  Furthermore, it seems to be sensible that an additional working day does not result in an increase of output of more than around 5 percent in general. Hence it might be appropriate to limit the effect by fixing the regression coefficient for the first period (Januar till November). At the same time putting restrictions on the other presumably smaller regression coefficient for December is not sensible. 

A second example can be given by the estimation of trading day effects in retail sales. Detailed research yielded that the decrease in turnover due to shop closing days depends strongly on the reason. The effect of Sundays is significantly higher than the effect of some public holidays. This can be modelled with a number of regressors. Nevertheless, the decline should not be larger than around 4 percent for a shop closing day regardless of the kind of holiday. With the same argumentation as aforementioned, it should be possible to restrict some regression effects by fixing while allowing the remaining to be estimated.

I have the impression that it could be possible to adjust the X13ModelBuilder.initializeUserHoliday. To fix only one of the userVariables there it is possible to distinguish the variables by their names. This solution has many site effects, the user interface and additional internal checks and many others I’m not aware of. 

This is an important feature for us. It would be great if you could add it and we would be willing to test it.
Regards Christiane and Andreas

**Comment by palatej** [comment]
Hi Christiane,

Fixing some coefficients in a group of regression variables has a lot of side effects. So, I will not investigate it in the short term. However, if you want to model your series in that way, you can always use simple User-defined regression variables instead of user-defined calendar effects.

**Comment by ChristianeHofer** [comment]
Hi Jean,
It’s a pity that my fear of the side effects was eligible. This was the reason why I didn’t dare to make the change on my own. 
After an internal discussion about your proposal, we came to the conclusion, that it is in general possible to use the user-defined regression variables. But then these variables are not grouped with the other calendar components. Therefore we would like to propose to reintroduce the user-defined variables with the component type calendar (but only for X13 specifications if possible). These user-defined variables must have fixed regression coefficients. Then these two groups of calendar variables can be treated separately and with some adjustments in the output all of them are used as calendars. This is a solution that has from our point of view fewer side effects than the first idea. We think that we can prepare a pull-request for the core and the app during the next two weeks. What do you think? Do you have any suggestions?

**Comment by ChristianeHofer** [comment]
Fixed with jdemetra/jdemetra-core#301 and jdemetra/jdemetra-core#300.
