### ISSUE TITLE
Suggestion: Remove [frozen] from SaItem

### ISSUE THREAD

**Issue by Immurb** [jdemetra/jdemetra-app#343]
Since the implementation of the reload functionality every SaItem is frozen almost all the time.
So I'm not sure if the "[frozen]" tag still contains useful information for the user.

**Comment by pinkfairystardust** [comment]
To me it seems that the [frozen] attribute to the time series works just as it supposed to work

**Comment by ChristianeHofer** [comment]
I have the impression that the status is (nearly) always frozen. When do you use this information?

**Comment by palatej** [comment]
When we introduced the "reload" facility, we had to face several problems. One of them was the updates of all the processing and derivations linked to the reloaded series. We decided to use frozen series for complex processing like seasonal adjustment, to avoid huge processing, possible circular references...
So, a reload will not update the "SaItems" displayed in a multi-document, which always refers to frozen series. We can of course remove the "[frozen]" tag in a multi-document, but the underlying series will differ from the initial series when it has been reloaded. So, it is perhaps not a good idea.
If you think that we really should remove the [frozen] suffix even if that can lead to some confusion, let me know...

**Comment by buerokrata** [comment]
Sorry for coming in late to this discussion, but I have the same issue with [frozen] in a multi-document. Practically all series are always frozen, whereas before I could interpret it as only being frozen when data came from the xml file; and unfrozen when data came through the provider.

The current [frozen] info is quite misleading after data has been refreshed through the provider...

**Comment by CHMcLaren** [comment]
I'm also coming late into this. I'm also finding the [frozen] label confusing in the multi-processing. I could be missing something obvious - but no matter what options I choose, it always appears as [frozen].
