### ISSUE TITLE
Fixed regression coefficient for Seasonal outlier

### ISSUE THREAD

**Issue by mancag** [jdemetra/jdemetra-app#345]
If I pre-specify a SO and fix the regression coefficient, then:
- In csv matrix output, everything is just like SO wouldn't be pre-specified: it isn't included in nout, noutso, out(1)/out(2)/out(3) ...
- Regressor SO (x-xxxx) isn't present among regressors, but I think it should be equal to the regressor SO (x-xxx) before the regression coefficient is fixed. Also, the following formula holds (e.g. for a multiplicative model):
ln out_s = t * SO (x-xxxx), where t is the fixed regression coefficient.

**Comment by palatej** [comment]
See #355
