### ISSUE TITLE
Fixed regression coefficient for Intervention variable

### ISSUE THREAD

**Issue by mancag** [jdemetra/jdemetra-app#346]
Intervention variable that doesn't have a fixed regression coefficient, has a regressor presented among other regressors.
But Intervention variable that has a fixed regression coefficient, doesn't have a regressor presented among other regressors, as it probably should be.

**Comment by palatej** [comment]
Fixed regression variables are handled in a completely different way than "normal" regression variables: they are removed from the series before any other computation and put back at the end of the modelling. Now, we could of course put them in the  different panels/output. That is not the current choice.
