### ISSUE TITLE
Diagnostics → Matrix

### ISSUE THREAD

**Issue by mancag** [jdemetra/jdemetra-app#349]
In JD+ 2.2.0 RC1, Diagnostics → Matrix might have some problems:
- Clicking on Diagnostics → Matrix confuses the software, so it has to be re-opened. (If I click on Diagnostics → Matrix (so that I can see what's there) and then click to e.g. Pre-processing, the content is changed (e.g. the ARIMA model is now (210)(111), although ARIMA model was fixed (011)(011) and the specification wasn't changed …). If I want to see the correct content again, I have to re-open JDemetra+ without saving changes.)
- Diagnostics → Matrix → tab Main: SE(res) should probably be equal to some (rounded) statistcs on Pre-processing → Residuals → Statistics, but none of them matches; the closest value is the value for Standard error (Details → 0 - Statistics), but not ok; also, on tab Custom, the residuals.ser is equal to SE(res), so also residuals.ser might be wrong.
- Diagnostics → Matrix → tab Custom: regression.nout, regression.noutso might have incorrect values, because the seasonal outlier fith fixed regression coefficient isn't taken into account.

**Comment by palatej** [comment]
It has been corrected in RC2
