### ISSUE TITLE
Export/Import Specifications

### ISSUE THREAD

**Issue by mancag** [jdemetra/jdemetra-app#350]
In my example, I exported my specification (myspec) from the first workspace and imported it to the second workspace. I noticed the following differences:
- myspec in the first workspace: 1. »Function Log« is inactive (grey); 2. Pre-specified seasonal outlier,
fixed regression coefficient for seasonal outlier; 3. Outliers are not enabled, Use default critical value is ticked, Critical value 3,5;
- myspec imported to the second workspace: 1. »Function Log« is active (black); 2. Pre-specified seasonal outlier, no fixed regression coefficient for seasonal outlier; 3. Outliers are not enabled, Use default critical value is not ticked, Critical value 2.

Also, TamoSeatsSpec-1.xml (from the first workspace) and myspec.xml (from the second workspace) differ from each other.
I applied the imported myspec to a new time series. The specification settings for this time series are the same as for the imported myspec.

**Comment by palatej** [comment]
Corrected in RC2.
See #315 (closed)
