### ISSUE TITLE
Suggestion (minor): Default value for Charset when opening txt files in providers window

### ISSUE THREAD

**Issue by saarinel** [jdemetra/jdemetra-app#366]
Providers –window – Txt files – Open – Open data source -dialogue:

Up to Jdemetra 2.0.0 default value of “windows-1252” for Charset, now default is “UTF-8”. When opening .txt-files this leads to the following error and data is not available. Changing back to "windows-1252" works just fine. (This is probably just to do with the scandic letters or something, but the previous default value seemed to suite our purposes). A screenshot and a text file used for testing are attached below.

**Screenshot**
![inputlengtherror](https://user-images.githubusercontent.com/28338554/27086373-ab819fe0-505a-11e7-9d2b-eb25ab993772.png)
**Example txt file**
[example.txt](https://github.com/jdemetra/jdemetra-app/files/1071688/example.txt)

**Comment by charphi** [comment]
If fact, the previous versions of JD+ used to read text files using the machine default charset.
This charset depends on the regional settings and so differs from machine to machine.
This might leads to inconsistent behaviour. 
To solve it, we have decided to set the default charset to UTF-8.

**Comment by saarinel** [comment]
Thank you for the explanation, makes perfect sense.
