### ISSUE TITLE
Annual totals test

### ISSUE THREAD

**Issue by MariaPetsch** [jdemetra/jdemetra-app#389]
Dear Developers,

More that one year ago we sent a question to the SAHelpDesk on cros-portal, and we haven't got any answer yet.

Our question was the following:
"We have some problems with annual totals test in JDemetra+, so we would like to ask some help from you. 
1.	We try to recalculate the annual totals test in excel but we cannot get the same result as the JDemetra+. We use the JDemetra+ Reference manual to do this, and make the following steps:
a.	calculate the annual totals of the original and seasonal adjusted series (summaries the four quarter year);
b.	calculate the absolute difference of the annual total series;
c.	calculate the maximum of the results from point b;
d.	calculate the Euclidian norm of the initial series (Here we are not sure what initial series exactly mean. Is this the original quarter year data, or the annual totals of the original series? We try to use both of them but none of them works.);
e.	we divided the result from point c with the result from point d.
2.	We make the calculation in point 1. because we thought, if we had known in which year we got the maximum value in point 1c it would have helped us to fix the problem. Do you think, it is a good way to start to solve the problem?
3.	At least we have a question about this test in general, and not connected with our problematic series. We would like to know whether we should use this test with indices series or not. Since the annual totals of the indices may not be interpretable, we are not sure that this test is good for this case."

We are looking forward for your answer.
Kind regards,
Gábor and Maria from HCSO

**Comment by palatej** [comment]
Hello,

The test just checks the discrepancies between the raw data and the seasonally adjusted data. It is based on the max absolute differences computed on full years. For more détails, see the code at https://github.com/jdemetra/jdemetra-core/blob/develop/jtss/src/main/java/ec/tss/sa/diagnostics/CoherenceDiagnostics.java [](url)

**Comment by palatej** [comment]
(lines 145...).
The test can of course be applied on any series.
Best regards

Jean

**Comment by MariaPetsch** [comment]
Thank you,
Maria
