### ISSUE TITLE
SAUG: jdemetra-2.2.1-rc2. 2 YearsForecast TS

### ISSUE THREAD

**Issue by maria-novas** [jdemetra/jdemetra-app#402]
If we set prediction lenght =-2, we obtain two years of forecasts for all the series in Table of Main results option. However, we only obtain one year of forecast for the following series:
1. Pre-adjustment series table of  Pre-processing option 
2. Series(lin) from Stochastic series table in Decomposition option. 

![forecast2years](https://user-images.githubusercontent.com/17139327/38506311-c0001bb2-3c19-11e8-9861-f92f6e31c5de.png)

**Comment by palatej** [comment]
Solved in jdemetra-core/#302

Jean
