### ISSUE TITLE
Refresh ("+ Arima parameters")

### ISSUE THREAD

**Issue by kidroger** [jdemetra/jdemetra-app#406]
Hello, 

I noticed that the behavior for Refresh "+ Arima parameters" option is different in what relates to the nospan option from the context menu (right-click) and doing the same from top menu.
Top menu : nospan = false;
Right-click menu: nospan = true;
This could mislead users to different results as option is the same, but results may or may not be the same.

Best Regards,
José Fernandes

**Comment by charphi** [comment]
The option `nospan` should indeed be false by default.
