### ISSUE TITLE
Suggestion: Ease of movement for workspaces and data across individuals

### ISSUE THREAD

**Issue by CHMcLaren** [jdemetra/jdemetra-app#409]
Within the XML information, the path for the data used is hardcoded into the SAProcessing.xml file. When working as part of training or demonstrations, this poses some challenges when the workspace is needed to be moved between individuals using their own laptops. e.g. instructor zipping the Calendars, SAprocessing, and TramoSeatsSpec (etc); and with the high level .xml file to transfer the information, and separately the data. The data used will likely be on different paths for everyone, so different users cannot update with new data easily as part of the refresh approach. It requires search and replace directly with the .xml files which can also lead to errors. Assuming I've not missed anything obvious - can JD+ be more flexible with changing or updating the data path in the workspace and enable the user to review or set this when opening workspaces without having to work with the .xml file directly.

**Comment by charphi** [comment]
This feature is already available in JD+: instead of using absolute paths to access input files, you can define relatives paths.
To do so, go to `Menu>Tools>Option>Demetra Paths`. There, you can manage the folders where the data is located.
For example, instead of using `C:\main_folder\sub_folder\data.xlsx` as data source, you could add `C:\main_folder\` in demetra paths and then add the data source `sub_folder\data.xlsx` in the providers tab.

**Comment by CHMcLaren** [comment]
fantastic. thanks!



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by CHMcLaren** [comment]
I'm missing something here as I'm still trying to get this working when transferring zipped files between different users. Does this approach for relative paths have to be used before starting a session? How does it work once a session (workspace) has already started and been created which has the full absolute path stored in the XML? 

e.g. within SAProcessing-1.xml I can see hardcoded 
<property name="@id" value="demetra://tsprovider/XCLPRVDR/20111201/SERIES?file=C%3A%5CUsers%5CUser%5CDocuments%5Cexample%5CData%5input.xls#seriesName=test1&sheetName=test"/>

Does the above approach over-ride this somehow? The absolute and relative paths would need to be the same for different users?

**Comment by CHMcLaren** [comment]
I'm still not getting this to work. Does this need to be set before starting the workspace? 
For example, in the SAprocessing-1.xml file I can see the full path hardcoded. Does the above approach over-ride this or need to be set before I start everything?

e.g. property name=xxx value="demetra://tsprovider/XCLPRVDR/20111201/SERIES?file=C%3A%5CUsers%5CUser%5CDocuments%5Ctest%5Cinput.xls#seriesName=test1&sheetName=test"

**Comment by charphi** [comment]
While it is possible to update by hand the original workspace (the one with absolute paths), this is not straightforward.
I would suggest to start over with a new workspace.

**Comment by charphi** [comment]
If you prefer to modify the original workspace, you can use the `workspace` command of jdemetra-cli.
(https://github.com/nbbrd/jdemetra-cli/wiki/cmd_workspace)

First, map the existing monikers, then edit manually the map file to change the paths.
Finaly, remap the monikers with the edited mapping.

Note that the manual editing may lead to errors if not done properly.
You should make backups before committing changes.

**Comment by CHMcLaren** [comment]
Thanks for the tip! The intention of my original enhancement / request was to make this a bit easier through a JD+ menu option, e.g. "Export" or "Move workspace" where the user could do what you suggest below but a bit slicker.


________________________________
