### ISSUE TITLE
short survey on using JDemetra+

### ISSUE THREAD

**Issue by pinkfairystardust** [jdemetra/jdemetra-app#418]
Dear all,

Me and my colleague Iulia Elena Toma , as young researchers, are performing a survey on using JDemetra+ for seasonal adjustment. We want to collect feedback on this software from as many users as possible with different backgrounds in order to determine what would make professionals, but not only them, recommend the  software. Please, kindly answer the following questions and distribute the link to anyone who may be interested.

https://goo.gl/forms/ggtyWPFlErY8uPq43

The aggregated results will be part of a short research article.

Thank you for your help!

**Comment by charphi** [comment]
Hi,

Thanks for doing this research.

Unfortunatly, this is not the right place to post this kind of requests.
Github issues are mainly used to report bugs or suggest new features.

I would suggest you to post it in the SAUG discussion group instead:
https://github.com/orgs/jdemetra/teams/saug 

Regards,
Philippe
