### ISSUE TITLE
Improvement: Output of xlsx does not work if there is a series with Status "NoData" and there is no warning.

### ISSUE THREAD

**Issue by LucienMay** [jdemetra/jdemetra-app#426]
If one imports an _.xls_ file in JDemetra+ with, say, 10 columns and one column contains no data (but a column name is present) then we get for this series a Status "NoData".

Exporting such a multi-document (_SAPProcessing-9-->Output--> .xls_) does not produce any _.xls_ output (which is OK), but no error message is generated.

It would be good to have in this case a message box/window indicating that no export is created, because the multi-document contains at least on series with Status "NoData", non-experienced users might otherwise not know what is the problem...

Version: JDemetra+ 2.2.1

**Comment by charphi** [comment]
There are actually two separate bugs:
- one that breaks the generation of the report if at least one series is empty
- one that prevents the error reporting if the error message is null

**Comment by charphi** [comment]
The 2 bugs should now be fixed and you can test it by downloading the latest JD+ snapshot at https://oss.jfrog.org/artifactory/oss-snapshot-local/eu/europa/ec/joinup/sat/nbdemetra-app/2.2.2-SNAPSHOT/nbdemetra-app-2.2.2-20180928.102137-9.zip
