### ISSUE TITLE
Bug: nbdemetra won't launch on macOS Mojave (10.14)

### ISSUE THREAD

**Issue by haginile** [jdemetra/jdemetra-app#430]
I successfully installed nbdemetra on macOS Mojava, but clicking on the icon doesn't launch the app. I'm using Java JDK 8. Unfortunately I'm not seeing a lot of logs being generated.

<img width="873" alt="screen shot 2018-10-15 at 16 17 38" src="https://user-images.githubusercontent.com/3156368/46975918-de1dce80-d095-11e8-8740-1a41f8868169.png">

**Comment by charphi** [comment]
I don't have macOS Mojave so I'm not able to test but here are a few things you can try:
- launch a terminal and type in `java -version` to check if Java is properly installed
- check the logs of JDemetra+ (see https://github.com/jdemetra/jdemetra-app/wiki/Quick-install-guide#troubleshooting)
- clear the cache
- ultimately, you can launch JDemetra+ by using the terminal. It might give you some insight about your problem

**Comment by haginile** [comment]
@charphi Thanks for the hints. I was able to resolve the issue by:

1. Upgrading Java to version 10.
2. Add `jdkhome="/Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home"` to `nbdemetra.conf`.
3. Do **NOT** add `default_options="-J--add-modules=java.xml.bind ..."` to `nbdemetra.conf`.

**Comment by haginile** [comment]
@charphi My apologies! `java.xml.bind` is indeed in `default_options` already. I'll update the comments above accordingly.
