### ISSUE TITLE
Open at the same time 2 JDemetra+ sessions

### ISSUE THREAD

**Issue by veroniqueelter** [jdemetra/jdemetra-app#435]
Hello, 

I wanted to ask if in a future version of JDemetra+, a possibility is foreseen, to open at least 2 sessions (workspaces) of JDemetra+ at the same time (like in Excel to open more files at the same time). This would be very helpful to compare manual adjustments made e.g. to the same series in different nomenclatures or by different users or between different campaigns. At the moment we have to open the old Wokspace write down the manual adjustment we did, open the new Workspace and redo the adjustment there. 

Best, Véronique

**Comment by charphi** [comment]
This is already possible by launching JD+ with a custom user dir. 
For example: `nbdemetra64.exe --userdir "C:\my_user_dir"`

See https://github.com/jdemetra/jdemetra-app/wiki/Quick-install-guide#a-few-tips
