### ISSUE TITLE
Problems starting 2.2.2-RC1 with Java 11

### ISSUE THREAD

**Issue by Immurb** [jdemetra/jdemetra-app#438]
I tried starting JD+ 2.2.2 RC1 with the Oracle JDK 11 (11.0.1+13-LTS) and with AdoptOpenJDK11 (also 11.0.1+13) and it shutdown without error message.

In the log I found the following error with both JDKs:
```
SEVERE [org.netbeans.core.modules]
java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:222)
Caused: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException starting from ModuleCL@173acc02[eu.europa.ec.joinup.sat.nbdemetra.core] with possible defining loaders null and declared parents [org.netbeans.MainImpl$BootClassLoader@51081592]
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:224)
	...
```

I think the problem is that JAXB API was removed from the JDK with Java 11 and it is "just" added as maven dependency with the scope "provided". So it compiles fine but can't find the needed classes at runtime.

**Comment by charphi** [comment]
Thanks for testing JD+ with Java 11.
JD+ is currently compilable with Java 11 but to run it with Java 11, you need extra steps : see https://github.com/jdemetra/jdemetra-app/wiki/Quick-install-guide#java-11-specific-instructions

**Comment by Immurb** [comment]
Oh okay missed that new part :sweat_smile: I put the "core"-folder in the "extra"-folder and it starts fine now. (Without changing the config) Thanks!
