### ISSUE TITLE
Bug: Creating "multiple" WorkspaceItem

### ISSUE THREAD

**Issue by Immurb** [jdemetra/jdemetra-app#44]
After using "Window" -> "Reset Windows" it seems that several WorkspaceItems are created when any new WorkspaceItem is made.
For each usage of "Reset Windows" the number of shown WorkspaceItems grows by one. So when you click it twice any creation of WorkspaceItems will seem to create three new Items instead of one. Furthermore any "rebuild" of the workspace e.g. "Sort" of multi-documents "deletes" the nonexistent Items.
This is just a visual bug but it's really confusing for the user.

**Comment by palatej** [comment]
See #214
