### ISSUE TITLE
JAVA_HOME environment variable

### ISSUE THREAD

**Issue by djhurio** [jdemetra/jdemetra-app#450]
It looks for me that JDemetra+ is ignoring the `JAVA_HOME` environment variable. I am in Windows 10. Is there a reason for this?

Usually software determines the location of Java according to the `JAVA_HOME` (or `JRE_HOME`) variable. For example it works for `RJDemetra`.

I can run JDemetra+ specifying the Java location
- using the `--jdkhome` switch for the `nbdemetra64.exe`;
- by editing the `etc/nbdemetra.conf` file.

**Comment by Immurb** [comment]
I am on Windows 7 and it takes `JAVA_HOME` if nothing is specified in `etc/nbdemetra.conf` or via `--jdkhome`.

**Comment by djhurio** [comment]
@Immurb, thanks for the information! Is `JAVA_HOME` user or system variable in your case? I have defined `JAVA_HOME` as a user variable. I do not have permission to modify system variables.

**Comment by charphi** [comment]
I've just tested on my Windows 10 with Oracle Java 8 installed and it ignores `JAVA_HOME`.
My guess is that the lookup of `java.exe` has some kind of priorities such as:
1. `--jdkhome` switch
2. `nbdemetra.conf` file
3. `PATH`
4. Windows registry
5. `JAVA_HOME`

**Comment by charphi** [comment]
@djhurio, user variables always overrides system variables

**Comment by Immurb** [comment]
@djhurio it is also a user variable for me, same restrictions

**Comment by djhurio** [comment]
I have `%JAVA_HOME\bin%` in my `PATH`, but it does not help.

**Comment by djhurio** [comment]
BTW, this works. Very interesting ;)

```
nbdemetra64.exe --jdkhome %JAVA_HOME%
```

**Comment by charphi** [comment]
Thanks for this tip. I might add it in the documentation.

**Comment by djhurio** [comment]
I confirm `JAVA_HOME` is ignored also on Windows 7 (x64). As you can see I have `JAVA_HOME` defined and I have Java in my `PATH`. R is recognising `JAVA_HOME` so `rJava` and `RJDemetra` works.

```
C:\Users\djhurio>echo %JAVA_HOME%
C:\Users\djhurio\Documents\OpenJRE\jdk8u212-b03-jre

C:\Users\djhurio>java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode)

C:\Users\djhurio>R.exe

R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> require(rJava)
Loading required package: rJava
> require(RJDemetra)
Loading required package: RJDemetra
> q()
Save workspace image? [y/n/c]: n
```

However if I run `nbdemetra64.exe` I am getting the error _Cannot find Java_ error.

![image](https://user-images.githubusercontent.com/744800/58294540-458dc080-7dd3-11e9-99ea-64a3e4d25158.png)

So the only way to run JDemetra+ is using the `nbdemetra64.exe --jdkhome %JAVA_HOME%` command.

Could this be fixed so that JDemetra+ would recognise `JAVA_HOME` variable?

**Comment by charphi** [comment]
JDemetra+ is build on a platform called NetBeans Platform.
That plaform deals with Java and we have no way to change its behavior.
So, we are not currently able to make JD+ recognise `JAVA_HOME`

**Comment by djhurio** [comment]
I see. I have found this bug report [NetBeans should use the JAVA_HOME and JDK_HOME environment variables, if available, to determine which JDK to use](https://netbeans.org/bugzilla/show_bug.cgi?id=198950). So as I understand NetBeans is not using `JAVA_HOME`.

> The launchers use a different strategy:
> 
> 1) --jdkhome
> 
> 2) netbeans_jdkhome in etc\netbeans.conf
> 
> 3) [on Windows] Windows Registry settings for CurrentVersion of Java (Software\JavaSoft\Java Development Kit)
> 
> 3) [on Linux] "javac" executable pointing to the JDK folder of the currently preferred JDK installation set by using "update-alternatives" utility
> 
> No plan to change the mechanism. You can always set the preferred JDK in netbeans.conf (as installer does for you) or start with --jdkhome parameter.

So this is closed. Thanks!

**Comment by charphi** [comment]
I've just added your tip to [Quick-install-guide[https://github.com/jdemetra/jdemetra-app/wiki/Quick-install-guide].
Thanks
