### ISSUE TITLE
Automatic installation of plugins

### ISSUE THREAD

**Issue by arnists** [jdemetra/jdemetra-app#451]
I can't find any documentation that shows how to install plugins without user interaction.

This would be a great feature for systems administrators to have.

**Comment by charphi** [comment]
I've just added a basic documentation on this subject at https://github.com/jdemetra/jdemetra-app/wiki/Plugins

**Comment by charphi** [comment]
@arnists  Is it ok for you? Can I close the issue?

**Comment by arnists** [comment]
I managed to make it work yes.
