### ISSUE TITLE
Refreshing arima parameters loses calendar settings

### ISSUE THREAD

**Issue by jabberbuggy** [jdemetra/jdemetra-app#467]
I have been using JDemetra+ to seasonally adjust time series. However when i set calendar settings with JDemetra+, for example:

Specifications -> REGRESSION -> Calendar:
Trading days: in use
automatic: WaldTest

And now when i choose Refresh -> Partial concurrent adjustment -> + Arima parameters over the series grid and then look at the calendar settings again, the "automatic" -setting has been set to "Unused", when it should be "WaldTest".

The problem seems to be due to the "estimationspec" element that JDemetra+ writes to the file SAProcessing-1.xml and it seems to override the original calendar settings. This is not good. Is there any way to fix this?

Best Regards,
Tapio

**Comment by palatej** [comment]
When you only re-estimate the Arima parameters, the regression variables are fixed and automatic trading days selection - among other things - is disabled. Use the "Complete" revision policy to retrieve your initial settings.
