### ISSUE TITLE
Data quality

### ISSUE THREAD

**Issue by NataliaSV** [jdemetra/jdemetra-app#471]
Hi! 
I have been using JDemetra for data quality.  I used to use the TERROR program. I need to validate if a new observation of a time series is congruent with existent data. I'm aware JDemetra has the Check Last Batch module, which is very helpful to my purpose. 

Because I am aiming to program this in R, I want to know if JDemetra presents the standard error of residuals somewhere? I want to replicate this number step by step.  The actual output shows the absolute value and the relative error, but I want to know the automatically calculated inputs to calculate the relative error and check if I am having the same results with R.

Than you for your help.
Natalia

**Comment by palatej** [comment]
Hello,

Sorry for this late answer.
What you need for reproducing TERROR is not the standard deviation of the residuals but the standard deviation of the forecasts (Terror estimates a model on a reduced set of data and compares the actual figures with the forecasts). The next release of jdlight ( a small R package based on JD+) will contain a function doing the job and providing all necessary information. Available at https://github.com/nbbrd/jdemetra-jdlight before the end of June 2020.
