### ISSUE TITLE
Bad non-seasonal forecast in Jdemetra

### ISSUE THREAD

**Issue by sakflex** [jdemetra/jdemetra-app#475]
I'm working with several monthly time series. The series go from January 2011 to the second month of every quarter in 2018 and 2019. What I want is to get a prediction for the third month in every quarter in both years. For instance:

· Data 01/2011 TO 02/2018 => forecast 03/18 (86 observations)
· Data 01/2011 TO 05/2018 => forecast 06/18 (89 observations)
· Data 01/2011 TO 08/2018 => forecast 09/18 (92 observations)
· Data 01/2011 TO 11/2018 => forecast 12/18 (95 observations)
(Same logic applies to 2019)

**The issue** is,  from 09/18 the automatic model works like a charm, from that date the forecasts are belor 0,5% desviation from the real data, either for non seasonally adjusted data or seasonally/calendar adjusted. 
However, for the two first quarters in 2018 this is not the case. In these cases, the forecast for the seasonally adjusted data is good as well, **but for non seasonally adjusted data is very poor**, with error above 2,5%. 

At first I thought it was a problem with the models (changing in the third term of 2018, performing well from that point). However, this is not the case, models do not change that much and applying models from 06/2018 to series from the two first terms do not change anything. Anyone has any clue on the root of this problem? Maybe below 90 observations Jdemetra forecast collapse?

**Comment by palatej** [comment]
Hello,

Forecasting is just forecasting. No model is able to give good forecasts all the time (except if your series is deterministic). The quality of forecasting should be measured against actual figures (not in comparison with seasonally adjusted data, which are “artificial” figures)
