### ISSUE TITLE
Current adjustment & Fixed model

### ISSUE THREAD

**Issue by djhurio** [jdemetra/jdemetra-app#507]
It looks to be a GUI bug under the _Refresh / Partial concurrent adjustment_ menu. The first item is named "Current adjustment" if the menu is opened with a right click. The first item is named "Fixed model" if the menu is opened from the top menu bar. See the attached images.

![image](https://user-images.githubusercontent.com/744800/79213135-53b45780-7e51-11ea-940b-775f092269d1.png)

![image](https://user-images.githubusercontent.com/744800/79213181-6af34500-7e51-11ea-8f78-f2a506979d72.png)

I am using:

```
Product Version: JDemetra+ 2.2.2
Java: 1.8.0_242; OpenJDK 64-Bit Server VM 25.242-b08
Runtime: OpenJDK Runtime Environment 1.8.0_242-b08
System: Windows 10 version 10.0 running on amd64; Cp1257; en_US (nbdemetra)
User directory: C:\Users\MLiberts\AppData\Roaming\.nbdemetra\dev
Cache directory: C:\Users\MLiberts\AppData\Roaming\.nbdemetra\dev\var\cache
```

**Comment by palatej** [comment]
OK. I see the bug (the actual refreshing policy is "fixed model"). It will be corrected in the next release, which will also contain the "current adjustment", based on additional additive outliers at the end of the series (the results are similar to the use of forecasts).
Thank you again.

Jean
