### ISSUE TITLE
Fixed regression coefficients

### ISSUE THREAD

**Issue by palatej** [jdemetra/jdemetra-app#51]
The coefficients of the regression variables are always re-estimated (included using the so-called "current seasonal adjustment"). An option to define and fix the coefficients will be added.

**Comment by duncanelliott** [comment]
copied below are comments relevant to this from a different closed issue

I would like to see this as an option before 3.x if possible (via fixed coefficients in user defined regressors?). Is there a case for not being able to meet the ESS guidelines if this is not included? For example, if there was a trading day effect in a series, this then stops at a particular point in time and you only want to estimate the effect using the span for which it was present. Other cases are when you know the actual value of an effect, why would you want to estimate it in a regression each time?

**Comment by palatej** [comment]
Being able to fix the coefficients is indeed sometimes important (for instance in the case of known outliers). From a statistical point of view the problem is simple: we just have to remove the defined regression effects before processing and to add them back at the end. The problem is elsewhere: what is the impact of a fixed regression coefficient on the other parameters of the specification: for instance:

  - should we fix all the regression coefficients (no), all the regression coefficients in a group of variables like trading days...?
  - obviously, log/level should be disabled; what about other automatic features? suppose that you fix the coefficients of the trading days; could we still estimate automatically (other) trading days effects? if you fix an outlier, do we need to search outliers at that point? ...

We could of course take a very pragmatic approach: everything is allowed, except the log/level, which is necessary because we want to fix the additive/multiplicative approach. Up to the user to select the right options. 

Finally, apart from those considerations, we have to solve the following (IT) problems:

- actual computation (simple) 
- integration in the graphical interface (tedious)
- xml serialization (compatibility with existing files)
- output (making the difference between fixed/estimated/total regression effects ?)
- ...

So, this issue is time consuming. Anyway, we can try to make a first simple implementation (see pragmatic approach) for 2.2. It will not be a waste of time.

**Comment by duncanelliott** [comment]
I like the sound of the pragmatic approach. Does it make it simpler to separate it completely from the regression effects and just require a separate series that is removed before pre-processing and then added back in (or not) if it is a permanent or temporary adjustment? You could even, if desired, specify whether this is additive/multiplicative adjustment and so not even effect log/level.

I can see a case for wanting to include fixed coefficients for certain spans within a time series and then allow them to be estimated for other parts, if you're seasonally adjusting a long series for example and effects have changed over time or you do not want to revise earlier points. This could also be useful if developing methods for evolving trading day effects, or testing for time varying regression coefficients?

**Comment by palatej** [comment]
See #275
