### ISSUE TITLE
Partial concurrent adjustment → Fixed model (don't fix user-defined calendar variables)

### ISSUE THREAD

**Issue by MargaritaNikolajeva6** [jdemetra/jdemetra-app#515]
Using _Partial concurrent adjustment → Fixed model_ it is not possible to fully fix the model due to  user-defined calendar variables. 
![3](https://user-images.githubusercontent.com/64843050/81067360-3f5efa00-8ee7-11ea-9ff3-f808fd317d88.JPG)

**Comment by palatej** [comment]
Thanks for your remark.
The problem will be corrected in JD+ 2.2.3
