### ISSUE TITLE
TC rate

### ISSUE THREAD

**Issue by MariaPetsch** [jdemetra/jdemetra-app#527]
We are using JDemetra+ version 2.2.0. According to the current situation we would like to modify the TC rate in some time series' model. We set the new value in specification then we checked the regressors' decay in the Pre-processing → Regressors part but nothing changed. Do we need to set a new value somehow or somewhere else, or is this a bug? If it was a bug, might it be repaired in the newest version of JD+? I attached a print screen about the problem.
![TC_rate_prob](https://user-images.githubusercontent.com/26739198/83484910-40635700-a4a6-11ea-83b8-5d2df62a3aa0.jpg)

**Comment by palatej** [comment]
Thank you.
You are right: TC rate is never updated. It will be corrected in JD+ 2.2.3

**Comment by MariaPetsch** [comment]
Thank you.
