### ISSUE TITLE
Outliers with fixed coefficient do not show up in the Matrix view/ CSV output in particular relevant for “Current [AO]”

### ISSUE THREAD

**Issue by Immurb** [jdemetra/jdemetra-app#535]
In the diagnostic view Matrix, fixed outliers are not included in the outliers count and are not displayed either. With the new revision policy “Current [AO]” in mind, this behaviour seems to “remove” outliers, especially in predefined reports e.g. CSV output or the RPackage, when using the new policy.
I think this behaviour is counter intuitive and can be seen as a bug, or should at least be very well documented.

**Comment by palatej** [comment]
Fixed regression variables (outlers, trading days...) are handled in a special way: they are removed from the series before the RegArima decomposition and added at the end of the processing. Also, by definition, they are not estimated and don't need to be put in diagnostics. Of course, that behavior could be discussed and changed in future releases (not in 2.x releases). 
Considering the "pseudo-additive outliers" in the "current [AO]" revision policy, it should be stressed that those variables are in fact handled as intervention variables and put in the user-variables group. That solution has been chosen for being able to distinguish them from "normal" outliers and to remove them properly. See the suitable outputs to retrieve them (csv matrix, custom diagnostics...). Of course we will document that behavior.
It should be stressed that the "Current [AO]" revision policy should only be used with caution and in very specific circumstances (from a statistical point of view, it is similar as ignoring the last observations).

**Comment by palatej** [comment]
A final comment:
The pseudo-additive outliers corresponding to the "Current[AO]" revision policy are never fixed. That solution has been chosen to allow re-estimation when recent raw figures are revised.
