### ISSUE TITLE
Missing scale on some charts

### ISSUE THREAD

**Issue by palatej** [jdemetra/jdemetra-app#57]
When a series contain very small values, the scale is not displayed correctly (only 0 is indicated). Probably a problem in JFreeChart.

**Comment by charphi** [comment]
Here is an example:

![missingscaleexample](https://cloud.githubusercontent.com/assets/8778378/10246662/9670f234-6913-11e5-93e4-af89a594f7f3.png)

Period | Value
------ | -----
1/01/1999 | 0,000272137
1/02/1999 | 0
1/03/1999 | 0,000204096
1/04/1999 | 0,000136059
1/05/1999 | 0,000272137
... | ...
