### ISSUE TITLE
Cannot open workspace 

### ISSUE THREAD

**Issue by LyubomiraD** [jdemetra/jdemetra-app#599]
When I try to open a workspace file I have the following error message:
![JDEM](https://user-images.githubusercontent.com/42490757/161539678-a15bf0ae-714a-4e18-b232-738e55623338.png)

The same workspace can be open on another computer with the same version of JDemetra + (2.2.2.)

**Comment by palatej** [comment]
What version of Java are you using?

**Comment by LyubomiraD** [comment]
1.8.0_301

**Comment by palatej** [comment]
Corrected in #699
