### ISSUE TITLE
Reload option for time series providers

### ISSUE THREAD

**Issue by palatej** [jdemetra/jdemetra-app#60]
The reload option for time series providers (for instance Excel workbooks) doesn't work.

**Comment by palatej** [comment]
Due to the internal design of JD+ (which uses caching, weak references...), this issue is complex. The solution we will consider (use of frozen time series where it is necessary) needs careful investigation.

**Comment by palatej** [comment]
Workload: 20 days

**Comment by charphi** [comment]
Fixed by #288
