### ISSUE TITLE
Settings of the diagnostics

### ISSUE THREAD

**Issue by palatej** [jdemetra/jdemetra-app#64]
The current diagnostics cannot be customized (modification of the thresholds...). Their settings will be available through the options dialog box

**Comment by charphi** [comment]
Example of dialog (from Demetra+):

![options-diagnostics](https://cloud.githubusercontent.com/assets/8778378/10339041/aecdb7fa-6d09-11e5-9b8b-dac694b387b2.png)

**Comment by charphi** [comment]
Work in progress: #79
