### ISSUE TITLE
Project installation problems

### ISSUE THREAD

**Issue by mskierski** [jdemetra/jdemetra-app#643]
I'm attempting to build the latest version of jdemetra branch v3.0.0 commit 82215b3c 
https://github.com/jdemetra/jdemetra-app. 

I'm getting the following problems with dependencies:

1. [ERROR] Non-resolvable import POM: eu.europa.ec.joinup.sat:demetra-parent:pom:3.0.0-SNAPSHOT was not found in https://oss.sonatype.org/content/repositories/snapshots/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of ossrh-snapshots has elapsed or updates are forced @ eu.europa.ec.joinup.sat:demetra-desktop-parent:3.0.0-SNAPSHOT, E:\Maciej\Source\Repos\jdemetra-app\pom.xml, line 70, column 25
2. [ERROR] 'dependencies.dependency.version' for com.github.nbbrd.java-service-util:java-service-processor:jar is missing. @ eu.europa.ec.joinup.sat:demetra-desktop-parent:3.0.0-SNAPSHOT, E:\Maciej\Source\Repos\jdemetra-app\pom.xml, line 263, column 21

Search at https://oss.sonatype.org/#nexus-search;quick~demetra indictes that the latest snapshot verions is 2.2.4

Am I missing something?

Thank you for your help
Regards
Maciej

**Comment by charphi** [comment]
Hi Maciej.
You need to build jdemetra-core first in order to be able to build jdemetra-app.
(jdemetra-code v3 snapshots are not deployed yet in a Maven repository)

**Comment by mskierski** [comment]
Dear Philip
Thank you very much for your answer.  

Which branch I should be using, that would give me the best change of succesfull build?

I tried master and run into a lot of problems with lombok, release version of netbeans and invalid repository repo.spring.io, 
The snapshots v3 are not in Maven. 

I assume that the only useable branch is "develop"? Is this the branch that is likely going to be the next release?

Sorry for trouble.
Thank you for your help

**Comment by charphi** [comment]
You need to use the v3.0.0 branch for both projects (jdemetra-core and jdemetra-app).
We will merge the v3.0.0 branches into develop later on.

**Comment by charphi** [comment]
For the record, all v3 code has been moved to its own repository : https://github.com/jdemetra/jdplus-main
