### ISSUE TITLE
Copy to spreadsheet not implemented

### ISSUE THREAD

**Issue by palatej** [jdemetra/jdemetra-app#655]
The copy of series to spreadsheets is not implemented.
See below (command from the providers tree)

![image](https://user-images.githubusercontent.com/8858782/197205555-ea605533-989a-4fed-a286-be9a1a25046b.png)

**Comment by charphi** [comment]
The problem appends when the filename extension is unknown. For example: `file.xyz` instead of `file.xlsx`.
This problem also exists in JD+ v2

**Comment by charphi** [comment]
Fixed in 834fed24f941a6fe05d25efe292a9970efd59837 and 8b057252fdc1a77a0b7efa2655a1e5ab9e22a750
