### ISSUE TITLE
How do I export JD+ OUPUT in JD+ version 2.2.4 or version 3.X?

### ISSUE THREAD

**Issue by ham4ssb** [jdemetra/jdemetra-app#785]
Hi 
In JD+ version 2.2.4 and version 3.X, I can’t see how I can export (save in files) seasonally adjusted data and trend, and diagnostics. In version 2.2.3, I managed that well. Is the functionality changed, am I missing something, or could there be an issue in later versions?

Also, we miss the possibility to save into files the main diagnostics from sliding span analysis and revision history analysis so it’s easy to also include them more automatically in quality reports. Now it seems that these diagnostic outputs are only visible in the GUI but not possible to save in files. 

Best regards 
Jørn Ivar Hamre (Statistics Norway)

**Comment by VabelGit** [comment]
Hi Ham4ssb, I just go to files, then save workspace as and then save it. I close then JDemetra and then open it from "Files-Open Workspace.

![image](https://github.com/jdemetra/jdemetra-app/assets/144357486/6b557024-366e-469a-a8ef-8fd268eff7eb)

Maybe if you can include a snap could be more helpful. I use Jdemetra 2.2.4

David

**Comment by VabelGit** [comment]
Okay, in my case it does not need to run again, just double-click the regression model and wait a few seconds, then in this part of the App I managed to recover the results.

![image](https://github.com/jdemetra/jdemetra-app/assets/144357486/822e5cd9-4969-4e14-afb0-c86f94cfd253)
