### ISSUE TITLE
Creating a new type of Excel output

### ISSUE THREAD

**Issue by LindaRZS** [jdemetra/jdemetra-app#802]
Hi, I'm new to JDemetra+ v2.2.4.
After finishing all the necessary analysis and ts decomposition I would like to save my output in an Excel file in one sheet, but the results for the purpose of my users should have a layout where all time series are arranged as a vertical list one bellow the other. Right now I achieve this by using other software for handling data/tables and rearrange the results in the desired layout.
Is this possible to upgrade JDemetra for this kind of output (saving results)?
Or could you point me in which direction should I try to make additional changes in the source code to achieve this kind of layout? 
I am grateful if you can guide me on how to solve this problem.

**Comment by charphi** [comment]
Hi, the version 2.x of JDemetra+ is in maintenance mode.
So, no more new features, only bug fixes.

To solve your problem, you would have to write a plugin but this is a lot of work and, as said above, this version is no more actively developed.

You should migrate to the version 3.x that is available at https://github.com/jdemetra/jdplus-main
