### ISSUE TITLE
data format in Txt files

### ISSUE THREAD

**Issue by AQLT** [jdemetra/jdemetra-app#820]
Is the Data format parameter working in JDemetra+ 2.2.4?
For example using the file [example_txt.csv](https://github.com/jdemetra/jdemetra-app/files/13271450/example_txt.csv) with the data format parameter yyyyMMDD doesn't allow to import data (only the first data of the year is imported). Note that it works in JDemetra+ 3.1.1.

**Comment by charphi** [comment]
JD+ v2.2.4 and v3.1.1 behave the same way.
Your problem comes from the use of an valid format. You should use `yyyyMMdd` instead of `yyyyMMDD`.

**Comment by AQLT** [comment]
Thanks, I was misled by the fact that the default format in JDemetra+ 2.4. is DD (and dd by default in 3.1).
