### ISSUE TITLE
Can't read `.ods` file

### ISSUE THREAD

**Issue by TanguyBarthelemy** [jdemetra/jdemetra-app#881]
Hi, 
I have an issue in reading `.ods` files.
I try to import it as a spreadsheet file:

![image](https://github.com/jdemetra/jdemetra-app/assets/112711017/76dc7619-a024-473e-ad38-ee76232fc94b)

So the file is placed in the `providers` panel and the sheet are recognised:

![image](https://github.com/jdemetra/jdemetra-app/assets/112711017/1c51fd9d-665e-4a14-ba01-221e4ca92471)

But that's all, the file is empty and the series are not read (when I click on the small `+` on the left, the sheet does not unroll with the series):

![image](https://github.com/jdemetra/jdemetra-app/assets/112711017/1616cb64-0093-4ba0-be50-dfc8fc7be455)

Maybe it's a bug or the `.ods` format is not accepted?
Is it possible to add a warning or an error in this case to inform the user that his file won't be read?

**Comment by TanguyBarthelemy** [comment]
The spreadsheet profiler is able to read my data but not my dates:

![image](https://github.com/jdemetra/jdemetra-app/assets/112711017/3951ab89-0c6f-4a01-8fe5-d1d13fcc6ba3)

**Comment by TanguyBarthelemy** [comment]
in V3 the problem remains the same as in V2 except thar we can explore the content of each sheet but the series are not available because the date is not read:

![image](https://github.com/jdemetra/jdemetra-app/assets/112711017/1620f07d-c0a1-40c8-a9de-69c508c6252c)

**Comment by TanguyBarthelemy** [comment]
Hi Philippe, 

I tested other`.ods` files creating this time by R (from the [**readODS**](https://github.com/ropensci/readODS) package).
I join you the two files (named `world_R.ods` and `world_excel_R.ods`).

For these two, the file contains one sheet named `Sheet1` but seems empty in the provider panel:

![image](https://github.com/jdemetra/jdemetra-app/assets/112711017/921e1fed-5182-436c-8da4-86b18511a488)

When I put these 2 files in the `Spreadsheet Profiler Windows`, I can read my dates:

for `world_R.ods`:

![image](https://github.com/jdemetra/jdemetra-app/assets/112711017/b88c4347-0032-4822-8f60-916c9b6f6b06)

for `world_excel_R.ods`:

![image](https://github.com/jdemetra/jdemetra-app/assets/112711017/ae6ca292-d6be-484b-8efa-3cb8d1eb8d24)

So as you can see it doesn't depends on the date format because these 2 files have differents date format.

The problem is the same in v3 except that in the providers tab, the series (colnames) appear but when I try to open them, "No data available".

**Comment by charphi** [comment]
The R example is a different problem.
The profiler shows that the date cells are in blue, meaning that is it a string type, not a date.
In order to parse these cells, you need to configure the "Data format" option (i.e. `yyyy-MM-dd`).

**Comment by charphi** [comment]
For the [world_libre_office.ods](https://github.com/jdemetra/jdemetra-app/files/15335858/world_libre_office.ods) file, the problem comes from the underlying library that is unable to handle `LocalDate` while being able to handle `LocalDateTime`.

I've created a new issue at https://github.com/nbbrd/spreadsheet4j/issues/470

**Comment by TanguyBarthelemy** [comment]
Thank you for your answer about the file .ods created with R. 

The date column was in the text format and needed a configuration of `Date format` option when importing (in **Providers** panel) the file.

**Comment by charphi** [comment]
The spreadsheet4j issue has been solved and will be integrated in the next bugfix release of JDemetra+ v2.
https://github.com/jdemetra/jdemetra-core/pull/1134
