### ISSUE TITLE
Can't use the main panel

### ISSUE THREAD

**Issue by TanguyBarthelemy** [jdemetra/jdemetra-app#882]
By manipulating the panels, I blocked access to the main panel. 

So at the moment I can't drag or open containers, SAPs or any graphical objects...

https://github.com/jdemetra/jdemetra-app/assets/112711017/444cb6a4-85c6-4f2e-a180-920b50d06e40

**Comment by charphi** [comment]
You can reset panels and windows by clicking on `Menu>Window>Reset Windows`

![2024-05-22 14_52_43](https://github.com/jdemetra/jdemetra-app/assets/8778378/d404c317-807f-40a0-8313-fb213d99d106)

**Comment by TanguyBarthelemy** [comment]
OK thank you very much!
